"""initial_schema

Revision ID: 79696726bbaa
Revises: 
Create Date: 2026-06-01 23:03:08.323552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79696726bbaa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centres',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_centres'))
    )
    op.create_index(op.f('ix_centres_code'), 'centres', ['code'], unique=True)
    op.create_index(op.f('ix_centres_id'), 'centres', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('children',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('aadhaar_number', sa.String(length=12), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_name', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('centre_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_children_centre_id_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    op.create_index(op.f('ix_children_aadhaar_number'), 'children', ['aadhaar_number'], unique=False)
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_users_centre_id_centres')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('attendance_records',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centres.id'], name=op.f('fk_attendance_records_centre_id_centres')),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_attendance_records_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    op.create_index(op.f('ix_attendance_records_centre_id'), 'attendance_records', ['centre_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_child_id'), 'attendance_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_session_date'), 'attendance_records', ['session_date'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_table('child_passports',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=False),
    sa.Column('current_risk_level', sa.String(length=10), nullable=False),
    sa.Column('current_risk_score', sa.String(length=10), nullable=False),
    sa.Column('total_attendance_sessions', sa.Integer(), nullable=False),
    sa.Column('attended_sessions', sa.Integer(), nullable=False),
    sa.Column('last_growth_recorded_at', sa.Date(), nullable=True),
    sa.Column('last_assessment_at', sa.Date(), nullable=True),
    sa.Column('active_referral_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_child_passports_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_child_passports')),
    sa.UniqueConstraint('child_id', name=op.f('uq_child_passports_child_id'))
    )
    op.create_index(op.f('ix_child_passports_id'), 'child_passports', ['id'], unique=False)
    op.create_index(op.f('ix_child_passports_passport_number'), 'child_passports', ['passport_number'], unique=True)
    op.create_table('development_assessments',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('assessed_date', sa.Date(), nullable=False),
    sa.Column('age_in_months', sa.Integer(), nullable=False),
    sa.Column('gross_motor_score', sa.Float(), nullable=False),
    sa.Column('fine_motor_score', sa.Float(), nullable=False),
    sa.Column('language_score', sa.Float(), nullable=False),
    sa.Column('cognitive_score', sa.Float(), nullable=False),
    sa.Column('social_emotional_score', sa.Float(), nullable=False),
    sa.Column('overall_milestone_score', sa.Float(), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.Column('developmental_status', sa.String(length=30), nullable=False),
    sa.Column('assessed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_development_assessments_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_development_assessments'))
    )
    op.create_index(op.f('ix_development_assessments_assessed_date'), 'development_assessments', ['assessed_date'], unique=False)
    op.create_index(op.f('ix_development_assessments_child_id'), 'development_assessments', ['child_id'], unique=False)
    op.create_index(op.f('ix_development_assessments_id'), 'development_assessments', ['id'], unique=False)
    op.create_table('growth_records',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('muac_cm', sa.Float(), nullable=True),
    sa.Column('weight_for_age_z', sa.Float(), nullable=True),
    sa.Column('height_for_age_z', sa.Float(), nullable=True),
    sa.Column('weight_for_height_z', sa.Float(), nullable=True),
    sa.Column('nutrition_status', sa.String(length=50), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_growth_records_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_records'))
    )
    op.create_index(op.f('ix_growth_records_child_id'), 'growth_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_growth_records_id'), 'growth_records', ['id'], unique=False)
    op.create_index(op.f('ix_growth_records_recorded_date'), 'growth_records', ['recorded_date'], unique=False)
    op.create_table('learning_activities',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('age_in_months', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('developmental_status', sa.String(length=30), nullable=False),
    sa.Column('centre_activities', sa.JSON(), nullable=False),
    sa.Column('home_activities', sa.JSON(), nullable=False),
    sa.Column('school_readiness_tasks', sa.JSON(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_learning_activities_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_activities'))
    )
    op.create_index(op.f('ix_learning_activities_child_id'), 'learning_activities', ['child_id'], unique=False)
    op.create_index(op.f('ix_learning_activities_id'), 'learning_activities', ['id'], unique=False)
    op.create_index(op.f('ix_learning_activities_plan_date'), 'learning_activities', ['plan_date'], unique=False)
    op.create_table('migration_history',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('from_centre_id', sa.UUID(), nullable=True),
    sa.Column('to_centre_id', sa.UUID(), nullable=False),
    sa.Column('migration_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_migration_history_child_id_children')),
    sa.ForeignKeyConstraint(['from_centre_id'], ['centres.id'], name=op.f('fk_migration_history_from_centre_id_centres')),
    sa.ForeignKeyConstraint(['to_centre_id'], ['centres.id'], name=op.f('fk_migration_history_to_centre_id_centres')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_history'))
    )
    op.create_index(op.f('ix_migration_history_child_id'), 'migration_history', ['child_id'], unique=False)
    op.create_index(op.f('ix_migration_history_id'), 'migration_history', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('child_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.String(length=5), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_notifications_child_id_children')),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name=op.f('fk_notifications_recipient_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_child_id'), 'notifications', ['child_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('parent_engagement_logs',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('engagement_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_parent_engagement_logs_child_id_children')),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name=op.f('fk_parent_engagement_logs_parent_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parent_engagement_logs'))
    )
    op.create_index(op.f('ix_parent_engagement_logs_child_id'), 'parent_engagement_logs', ['child_id'], unique=False)
    op.create_index(op.f('ix_parent_engagement_logs_id'), 'parent_engagement_logs', ['id'], unique=False)
    op.create_index(op.f('ix_parent_engagement_logs_parent_id'), 'parent_engagement_logs', ['parent_id'], unique=False)
    op.create_table('referrals',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('referral_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('referred_to', sa.String(length=255), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_referrals_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referrals'))
    )
    op.create_index(op.f('ix_referrals_child_id'), 'referrals', ['child_id'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_table('risk_scores',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('attendance_score', sa.Float(), nullable=False),
    sa.Column('nutrition_score', sa.Float(), nullable=False),
    sa.Column('development_score', sa.Float(), nullable=False),
    sa.Column('caregiver_score', sa.Float(), nullable=False),
    sa.Column('migration_score', sa.Float(), nullable=False),
    sa.Column('contributing_factors', sa.JSON(), nullable=False),
    sa.Column('weight_breakdown', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('calculated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_risk_scores_child_id_children')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_scores'))
    )
    op.create_index(op.f('ix_risk_scores_child_id'), 'risk_scores', ['child_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_id'), 'risk_scores', ['id'], unique=False)
    op.create_table('referral_status_logs',
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('fk_referral_status_logs_referral_id_referrals')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_status_logs'))
    )
    op.create_index(op.f('ix_referral_status_logs_id'), 'referral_status_logs', ['id'], unique=False)
    op.create_index(op.f('ix_referral_status_logs_referral_id'), 'referral_status_logs', ['referral_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_status_logs_referral_id'), table_name='referral_status_logs')
    op.drop_index(op.f('ix_referral_status_logs_id'), table_name='referral_status_logs')
    op.drop_table('referral_status_logs')
    op.drop_index(op.f('ix_risk_scores_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_child_id'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_child_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_parent_engagement_logs_parent_id'), table_name='parent_engagement_logs')
    op.drop_index(op.f('ix_parent_engagement_logs_id'), table_name='parent_engagement_logs')
    op.drop_index(op.f('ix_parent_engagement_logs_child_id'), table_name='parent_engagement_logs')
    op.drop_table('parent_engagement_logs')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_child_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_migration_history_id'), table_name='migration_history')
    op.drop_index(op.f('ix_migration_history_child_id'), table_name='migration_history')
    op.drop_table('migration_history')
    op.drop_index(op.f('ix_learning_activities_plan_date'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_id'), table_name='learning_activities')
    op.drop_index(op.f('ix_learning_activities_child_id'), table_name='learning_activities')
    op.drop_table('learning_activities')
    op.drop_index(op.f('ix_growth_records_recorded_date'), table_name='growth_records')
    op.drop_index(op.f('ix_growth_records_id'), table_name='growth_records')
    op.drop_index(op.f('ix_growth_records_child_id'), table_name='growth_records')
    op.drop_table('growth_records')
    op.drop_index(op.f('ix_development_assessments_id'), table_name='development_assessments')
    op.drop_index(op.f('ix_development_assessments_child_id'), table_name='development_assessments')
    op.drop_index(op.f('ix_development_assessments_assessed_date'), table_name='development_assessments')
    op.drop_table('development_assessments')
    op.drop_index(op.f('ix_child_passports_passport_number'), table_name='child_passports')
    op.drop_index(op.f('ix_child_passports_id'), table_name='child_passports')
    op.drop_table('child_passports')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_records_session_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_child_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_centre_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_index(op.f('ix_children_aadhaar_number'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_centres_id'), table_name='centres')
    op.drop_index(op.f('ix_centres_code'), table_name='centres')
    op.drop_table('centres')
    # ### end Alembic commands ###
